name: Generate Data and Send Email Every Monday

on:
  schedule:
    # Runs at 8:00 AM UTC every Monday
    - cron: '0 8 * * MON'

jobs:
  generate-and-email:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify your Python version if needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Data Generation Script
        run: python generate_data.py

      - name: Run Email Script
        run: python send_email.py
