name: Generate Data and Send Email Every Monday

on:
  schedule:
    - cron: '0 4 * * MON'  # Runs at 4:00 AM UTC every Monday, which is 9:30 AM IST
  workflow_dispatch:        # Allows manual trigger

jobs:
  generate-and-email:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Data Generation Script
        run: python generate_data.py

      - name: Run Email Script
        if: success()  # Only runs if the previous step was successful
        run: python send_email.py
